# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js image for building the application
FROM node:14-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the project files
COPY . .

# Build the project
RUN npm run build

# Use a lighter Node.js image to run the application
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app/build ./build

# Copy package.json and package-lock.json for production install
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Set environment variables
ENV GOOGLE_CLIENT_ID=your_client_id
ENV GOOGLE_CLIENT_SECRET=your_client_secret
ENV GOOGLE_REFRESH_TOKEN=your_refresh_token

# Run the server
CMD ["node", "build/index.js"]